// MARK: - FinishedImageLook
//
// The Enhanced look (and HDR) for cameras that hand us a FINISHED image
// rather than raw Bayer data — the QuickTake 200 / Fujifilm DS-7 family,
// which stores ordinary JPEGs on a SmartMedia card.
//
// There is no Bayer decode to hook into for those, and nothing for the
// Kodak colour matrix or transfer curve to do: the camera did all of that
// in 1997. What IS still applicable is the post-process, because those
// four steps are perceptual-domain and scale-invariant — they work on any
// gamma-encoded RGB.
//
// So this file owns exactly one thing the QTK path doesn't: the sRGB
// transfer curve. The enhancement itself is `QTKDecoder.applyEnhancement`,
// called rather than copied. A second copy of those steps is precisely how
// Enhanced came to be silently skipped in HDR.
//
// One honest caveat about what HDR means here. On the QTK path some of the
// above-white content is real — the colour matrix overshoots on saturated
// colours. A finished JPEG has none of that: it is 8-bit sRGB, clipped at
// white before we ever see it. So for the QT200 the headroom is entirely
// generated by the enhancement's own overshoot (clarity and saturation
// pushing highlights up). That is the same mechanism that produces most of
// the QTK enhanced headroom too, so it is consistent — but it is creating
// range, not recovering it.

import Foundation
import AppKit
import CoreGraphics

nonisolated enum FinishedImageLook {

    /// sRGB EOTF, extended past white along its slope at 1.0 so the
    /// enhancement's overshoot stays ordered and invertible instead of
    /// collapsing onto white. Same treatment the Kodak curve gets.
    @inline(__always)
    static func srgbToLinear(_ v: Double) -> Double {
        if v <= 0.0 { return 0.0 }
        if v > 1.0 {
            // d/dv of the sRGB curve at v = 1 is 2.4/1.055 ≈ 2.2749.
            return 1.0 + (v - 1.0) * (2.4 / 1.055)
        }
        return v <= 0.04045 ? v / 12.92 : pow((v + 0.055) / 1.055, 2.4)
    }

    /// Apply the look to an already-decoded image.
    ///
    /// `enhanced == false && hdr == false` is a no-op by design: the
    /// vintage look for these cameras IS the camera's own JPEG, untouched.
    static func render(_ cg: CGImage,
                       enhanced: Bool,
                       hdr: Bool,
                       headroom: Double,
                       recipe: EnhancementRecipe = .finished) -> NSImage? {
        guard enhanced || hdr else {
            return NSImage(cgImage: cg, size: NSSize(width: cg.width, height: cg.height))
        }

        let w = cg.width, h = cg.height
        let pixelCount = w * h
        guard pixelCount > 0 else { return nil }

        // Draw into a known layout rather than trusting the JPEG's own —
        // ImageIO can hand back any component order or bit depth.
        var rgba8 = [UInt8](repeating: 0, count: pixelCount * 4)
        guard let srgb = CGColorSpace(name: CGColorSpace.sRGB) else { return nil }
        let drawn: Bool = rgba8.withUnsafeMutableBytes { buf in
            guard let ctx = CGContext(
                data: buf.baseAddress, width: w, height: h,
                bitsPerComponent: 8, bytesPerRow: w * 4, space: srgb,
                bitmapInfo: CGImageAlphaInfo.noneSkipLast.rawValue) else { return false }
            ctx.draw(cg, in: CGRect(x: 0, y: 0, width: w, height: h))
            return true
        }
        guard drawn else { return nil }

        var rgb = [Float](repeating: 0, count: pixelCount * 3)
        for i in 0..<pixelCount {
            rgb[i*3]     = Float(rgba8[i*4])     / 255
            rgb[i*3 + 1] = Float(rgba8[i*4 + 1]) / 255
            rgb[i*3 + 2] = Float(rgba8[i*4 + 2]) / 255
        }

        if enhanced {
            rgb = QTKDecoder.applyEnhancement(rgb, width: w, height: h, recipe: recipe)
        }

        return hdr ? renderHDR(rgb, w: w, h: h, headroom: headroom)
                   : renderSDR(rgb, w: w, h: h, colorSpace: srgb)
    }

    // MARK: - Outputs

    private static func renderSDR(_ rgb: [Float], w: Int, h: Int,
                                  colorSpace: CGColorSpace) -> NSImage? {
        let n = w * h
        var out = [UInt8](repeating: 255, count: n * 4)
        for i in 0..<n {
            out[i*4]     = UInt8(max(0, min(255, rgb[i*3]     * 255)))
            out[i*4 + 1] = UInt8(max(0, min(255, rgb[i*3 + 1] * 255)))
            out[i*4 + 2] = UInt8(max(0, min(255, rgb[i*3 + 2] * 255)))
        }
        return image(from: out, w: w, h: h, bitsPerComponent: 8, bitsPerPixel: 32,
                     bytesPerRow: w * 4, space: colorSpace,
                     info: CGBitmapInfo(rawValue: CGImageAlphaInfo.noneSkipLast.rawValue))
    }

    private static func renderHDR(_ rgb: [Float], w: Int, h: Int,
                                  headroom: Double) -> NSImage? {
        guard let space = CGColorSpace(name: CGColorSpace.extendedLinearSRGB) else { return nil }
        let n = w * h
        var half = [UInt16](repeating: 0, count: n * 4)
        for i in 0..<n {
            for c in 0..<3 {
                let lin = srgbToLinear(Double(rgb[i*3 + c]))
                half[i*4 + c] = QTKDecoder.float16Bits(
                    Float(QTKDecoder.hdrToneMap(lin, headroom: headroom)))
            }
            half[i*4 + 3] = QTKDecoder.float16Bits(1.0)
        }
        return image(from: half, w: w, h: h, bitsPerComponent: 16, bitsPerPixel: 64,
                     bytesPerRow: w * 8, space: space,
                     info: [CGBitmapInfo(rawValue: CGImageAlphaInfo.noneSkipLast.rawValue),
                            .floatComponents, .byteOrder16Little])
    }

    private static func image<T>(from buffer: [T], w: Int, h: Int,
                                 bitsPerComponent: Int, bitsPerPixel: Int,
                                 bytesPerRow: Int, space: CGColorSpace,
                                 info: CGBitmapInfo) -> NSImage? {
        let bytes = buffer.withUnsafeBufferPointer { Data(buffer: $0) }
        guard let provider = CGDataProvider(data: bytes as CFData),
              let cg = CGImage(width: w, height: h,
                               bitsPerComponent: bitsPerComponent,
                               bitsPerPixel: bitsPerPixel,
                               bytesPerRow: bytesPerRow,
                               space: space, bitmapInfo: info,
                               provider: provider, decode: nil,
                               shouldInterpolate: false, intent: .defaultIntent)
        else { return nil }
        return NSImage(cgImage: cg, size: NSSize(width: w, height: h))
    }
}

/// The Look as a plain value, so it can be captured by the detached decode
/// tasks the import loop runs.
nonisolated struct FinishedLookSettings: Sendable {
    let enhanced: Bool
    let hdr: Bool
    let headroom: Double

    /// A no-op pass: `FinishedImageLook.render`/`PanoramaComposition.finished`
    /// both short-circuit on `enhanced == false && hdr == false`, returning
    /// the source image untouched. Named for call sites that must leave an
    /// already-finished source exactly as it was decoded.
    static let neutral = FinishedLookSettings(enhanced: false, hdr: false, headroom: 1.0)
}
